import json, re, hashlib
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urljoin
import requests
from bs4 import BeautifulSoup

SOURCES=[
 ('AÇA Türkiye','https://aca.csb.gov.tr/','career'),
 ('EEA Careers','https://www.eea.europa.eu/en/about/careers/vacancies','career'),
 ('Copernicus Land News','https://land.copernicus.eu/en/news','eo'),
 ('Copernicus Land Products','https://land.copernicus.eu/en/products','learn'),
 ('Copernicus Data Space News','https://dataspace.copernicus.eu/news','eo'),
 ('Copernicus Data Space APIs','https://documentation.dataspace.copernicus.eu/APIs.html','learn'),
 ('Eionet','https://www.eionet.europa.eu/','eionet'),
 ('Eionet Dataflows','https://www.eionet.europa.eu/reportnet/dataflows','learn'),
]
OUT=Path('docs/data/items.json'); HEAD={'User-Agent':'EuroScope/3.1 (+personal learning radar)'}
KEYWORDS=['sne','seconded national expert','ulusal uzman','geçici görevli','vacanc','expert','copernicus','sentinel','openeo','api','dataset','product','eionet','reportnet','earth observation','land cover','urban atlas','ground motion','climate','water','vegetation','soil','stac','odata','jupyter','algorithm','corine','insar','tropomi']

LESSONS=[
 {'topic':'Sentinel-1: radar gözünden Dünya','category':'Sentinel / SAR','what':'Sentinel-1, C-band sentetik açıklıklı radar (SAR) kullanan Copernicus görevidir. Optik bir kamera gibi yansıyan güneş ışığını ölçmek yerine kendi mikrodalga sinyalini gönderip yüzeyden dönen sinyali kaydeder. Bu nedenle gece-gündüz çalışabilir ve bulutluluk optik sistemlere göre çok daha az sorun yaratır.','why':'Sentinel-1 yalnızca bir “radar görüntüsü” kaynağı değildir. GRD ürünleri taşkın, kıyı ve arazi değişimi gibi uygulamalarda; SLC ürünleri ise faz bilgisini koruduğu için interferometri ve yüzey deformasyonu çalışmalarında kritik rol oynar.','access':'Copernicus Data Space Browser ile görsel keşif yapabilir; STAC/OData ile ürün arayabilir; Python/openEO gibi araçlarla iş akışını otomatikleştirebilirsin. InSAR için ürün tipini ve yörünge geometrisini özellikle doğru seçmek gerekir.','you':'PS-InSAR deneyiminle doğrudan bağlantılı. Yeni bir bölgeyi sıfırdan işlemek yerine Copernicus EGMS sonuçlarıyla kendi InSAR sonuçlarını karşılaştırarak yöntem doğrulaması ve ölçek karşılaştırması yapabilirsin.','idea':'Bir maden/heyelan alanında kendi PS-InSAR hız alanın ile EGMS hızlarını; mekânsal kapsama, LOS hızları, anomali konumları ve veri yoğunluğu açısından karşılaştır.','details':'Sentinel-1 verisini okurken dört şeyi birlikte düşün: ürün seviyesi, çekim modu, polarizasyon ve yörünge. GRD genlik bilgisini pratik biçimde sunar; SLC ise kompleks veri ve faz bilgisini korur. IW modu kara uygulamalarında en sık karşılaşacağın moddur. VV/VH gibi polarizasyonlar yüzey pürüzlülüğü, yapı ve nem koşullarına farklı duyarlılık gösterir. InSAR tarafında iki görüntünün faz farkından doğrudan dikey hareket ölçülmez; ölçüm sensörün bakış doğrultusundaki LOS bileşenidir. Bu nedenle ascending/descending geometri ve referans noktası yorumda önemlidir.','workflow':'1) Araştırma sorusunu belirle. 2) Uygun SLC/GRD ürününü seç. 3) Aynı yörünge/geometriyi koru. 4) Kalite ve ön işlem adımlarını uygula. 5) Sonucu EGMS gibi bağımsız ürünlerle karşılaştır.','limits':'Radarın buluttan etkilenmemesi her yüzeyde kusursuz sonuç verdiği anlamına gelmez. Bitki örtüsü, kar, hızlı yüzey değişimi ve zamansal dekorrelasyon interferometrik tutarlılığı düşürebilir.','concepts':'SAR · SLC/GRD · LOS · InSAR','url':'https://dataspace.copernicus.eu/explore-data/data-collections/sentinel-data/sentinel-1'},
 {'topic':'Sentinel-2: 13 bant neden önemli?','category':'Sentinel / Optik','what':'Sentinel-2, kara ve kıyı alanlarını 13 spektral bantla gözleyen optik Copernicus görevidir. Bantların mekânsal çözünürlükleri 10, 20 ve 60 metredir. Görünür, yakın kızılötesi ve red-edge bantlarının birlikte bulunması bitki, su, yangın ve arazi örtüsü analizlerinde onu çok kullanışlı yapar.','why':'NDVI, NBR veya NDCI gibi indeksler yalnızca formül değildir; hangi bantların hangi fiziksel özelliğe duyarlı olduğunu anlamak gerekir. Level-2A yüzey yansıtımı atmosfer etkileri düzeltilmiş analizler için çoğu kara uygulamasında daha uygun başlangıç ürünüdür.','access':'CDSE Browser, STAC/OData ve Sentinel Hub servislerinden erişilebilir. GEE üzerinde de Sentinel-2 koleksiyonları bulunur; fakat EuroScope sana CDSE tarafındaki erişim ve işleme yollarını da öğretecek.','you':'Yangın sonrası NBR/NDVI ve kıyı su kalitesi çalışmalarınla doğrudan ilişkili. Aynı analizi CDSE/openEO tarafında tekrar etmek, tek bir platforma bağımlı olmayan bir EO iş akışı kurmanı sağlar.','idea':'Aynı Sentinel-2 zaman serisini GEE ve CDSE/openEO ile üret; veri seçimi, bulut maskeleme, tekrarlanabilirlik ve çıktı tutarlılığını karşılaştır.','details':'Sentinel-2 MSI sensörü 13 bant taşır. 10 m bantlar görünür ve NIR ayrıntısını; 20 m bantlar red-edge ve SWIR bilgisini; 60 m bantlar ise özellikle atmosferik düzeltmeye yardımcı olan daha kaba çözünürlüklü kanalları içerir. L1C ürün TOA yansıtımıdır; L2A ise atmosferik düzeltme sonrası BOA yüzey yansıtımını hedefler. NDVI bitki canlılığına, NBR yangın etkisine, NDWI türevleri su/nem özelliklerine duyarlıdır; fakat indeks değeri tek başına fiziksel gerçeğin tamamı değildir.','workflow':'1) L2A koleksiyonunu seç. 2) Bulut/gölge kalite bilgisini kullan. 3) AOI ve tarihi filtrele. 4) İndeksi hesapla. 5) Mevsimsellik ve arazi sınıfını dikkate al. 6) Mümkünse saha/kurumsal veriyle doğrula.','limits':'Bulut, gölge, kıyı pikselleri, sığ su tabanı ve atmosferik etkiler indeksleri yanıltabilir. Farklı tarihler karşılaştırılırken mevsim ve görüntü geometrisi göz ardı edilmemeli.','concepts':'L1C · L2A · red-edge · surface reflectance','url':'https://dataspace.copernicus.eu/explore-data/data-collections/sentinel-data/sentinel-2'},
 {'topic':'Sentinel-3: kıyı ve çevre izlemede farklı ölçek','category':'Sentinel / Okyanus-Kara','what':'Sentinel-3; okyanus rengi, kara/deniz yüzey sıcaklığı ve yüzey özelliklerini izleyen çok sensörlü bir görevdir. Sentinel-2 kadar yüksek mekânsal çözünürlük hedeflemez; bunun yerine geniş alanı sık tekrarlarla gözlemek çevresel zaman serileri için avantaj sağlar.','why':'Bir sensörün “daha yüksek çözünürlüklü” olması her zaman daha iyi olduğu anlamına gelmez. Kıyı su kalitesi gibi konularda Sentinel-2 mekânsal ayrıntı sağlarken Sentinel-3 daha sık ve geniş ölçekli çevresel gözlem sağlayabilir.','access':'CDSE üzerinden Sentinel-3 koleksiyonları keşfedilebilir ve indirilebilir. Ürün seçerken sensör ve ürün tipini araştırma sorusuna göre ayırmak gerekir.','you':'İzmir Körfezi çalışmanda Sentinel-2 tabanlı göstergelerin yanına Sentinel-3 deniz rengi ürünlerini eklemek, tek sensörlü analizden çok-sensörlü bir çalışmaya geçiş sağlar.','idea':'İzmir Körfezi için Sentinel-2 ve Sentinel-3 tabanlı klorofil göstergelerinin mekânsal ve zamansal uyumunu istasyon verileriyle değerlendir.','concepts':'OLCI · SLSTR · ocean colour · temporal resolution','url':'https://dataspace.copernicus.eu/explore-data/data-collections/sentinel-data/sentinel-3'},
 {'topic':'Sentinel-5P + TROPOMI: atmosferi haritalamak','category':'Atmosfer','what':'Sentinel-5P üzerindeki TROPOMI sensörü NO₂, SO₂, CO, CH₄, ozon, formaldehit ve aerosol gibi atmosfer bileşenlerini küresel ölçekte izler. Bu ürünler doğrudan yer seviyesi hava kalitesi istasyonu ölçümü değildir; atmosferik kolon bilgisini temsil eden ürünlerin fiziksel anlamı analizden önce anlaşılmalıdır.','why':'Uydu atmosfer ürünlerinde kalite bayrakları ve qa_value gibi değişkenler kritik önemdedir. Haritayı doğrudan ortalamak yerine düşük kaliteli gözlemleri elemek, bulut ve ölçüm geometrisi etkilerini dikkate almak gerekir.','access':'CDSE üzerinde Sentinel-5P koleksiyonlarına erişilebilir; bazı Level-2 koleksiyonları openEO ile sunucu tarafında işlenebilir. Böylece büyük zaman serilerini tek tek dosya indirmeden analiz etmek mümkündür.','you':'CBS + iklim/çevre profilin için yeni bir araştırma hattı açar. Arazi kullanımı, ulaşım veya sanayi katmanlarını atmosfer gözlemleriyle ilişkilendirerek EO ile politika/şehir çalışmalarını birleştirebilirsin.','idea':'Ankara’da 2019–2026 NO₂ mevsimselliğini CLMS arazi örtüsü ve ana ulaşım koridorlarıyla birlikte incele; uydu ürününün sınırlılıklarını ayrıca tartış.','concepts':'TROPOMI · L2 · qa_value · tropospheric column','url':'https://dataspace.copernicus.eu/explore-data/data-collections/sentinel-data/sentinel-5p'},
 {'topic':'openEO: veriyi indirmeden analiz etmek','category':'API / Bulut İşleme','what':'openEO, Earth Observation verilerini standart bir API üzerinden sunucu tarafında işlemek için geliştirilmiş açık bir arayüzdür. Kullanıcı veri küpünü, mekânsal-zamansal filtreleri ve işlemleri tanımlar; hesaplama verinin bulunduğu altyapıda yapılır.','why':'STAC/OData ile openEO aynı iş değildir. STAC ve OData ağırlıklı olarak veri keşfi/katalog erişimi sağlarken openEO analiz sürecini de tanımlayabilir. Bu ayrımı bilmek CDSE ekosistemini gerçekten anlamanın temelidir.','access':'Python istemcisiyle bir backend’e bağlanıp koleksiyonları listeleyebilir, AOI/tarih seçebilir, bant işlemleri ve zamansal indirgeme yapabilir ve sonuç işi oluşturabilirsin.','you':'GEE deneyimini Copernicus’un kendi ekosistemine taşımanın en mantıklı yollarından biri. CV’de yalnız “Sentinel kullandım” yerine bulut tabanlı EO processing workflow gösterebilirsin.','idea':'Bir Sentinel-2 indeks zaman serisini hem GEE hem openEO ile üret; veri seçimi, kod yapısı, tekrarlanabilirlik ve işlem yaklaşımını teknik olarak karşılaştır.','concepts':'data cube · process graph · batch job · backend','url':'https://documentation.dataspace.copernicus.eu/APIs/openEO.html'},
 {'topic':'STAC ve OData: katalog API’si ne demek?','category':'API / Veri Keşfi','what':'STAC, mekânsal-zamansal varlıkları standart JSON yapılarıyla tanımlayan açık bir katalog yaklaşımıdır. OData ise CDSE kataloğunda ürünleri özelliklerine göre sorgulamak ve erişmek için kullanılan başka bir API yoludur. İkisi de “uydu görüntüsünü analiz eden algoritma” değildir; öncelikle doğru veriyi bulma ve erişim problemini çözer.','why':'Manuel Browser kullanımı birkaç görüntü için yeterlidir. Yüzlerce tarih, farklı AOI veya tekrarlanan araştırma akışı olduğunda programatik katalog sorgusu araştırmanın tekrarlanabilirliğini ciddi biçimde artırır.','access':'Python/Colab içinde tarih, geometri, koleksiyon ve ürün özelliklerine göre sorgu kurup sonuç URL/kimliklerini sonraki indirme veya işleme adımına aktarabilirsin.','you':'Afet öncesi/sonrası veya uzun zaman serisi analizlerinde veri toplama aşamasını otomatikleştirmen için yararlı.','idea':'Türkiye’de seçilen herhangi bir afet AOI’si için olay tarihinden önce/sonra uygun Sentinel ürünlerini otomatik bulan küçük bir “EO Data Finder” geliştir.','concepts':'catalogue · collection · item · spatial/temporal query','url':'https://documentation.dataspace.copernicus.eu/APIs.html'},
 {'topic':'CLMS: Copernicus sadece ham uydu görüntüsü değildir','category':'Copernicus Land','what':'Copernicus Land Monitoring Service (CLMS), ham uydu görüntülerinin ötesinde arazi örtüsü/arazi kullanımı, biyofiziksel değişkenler, referans veriler ve yer hareketi gibi temalarda hazır ürün ve servisler sağlar. CORINE Land Cover, Urban Atlas ve European Ground Motion Service bunun farklı tipte örnekleridir.','why':'Araştırmada her değişkeni Sentinel görüntüsünden kendin üretmek zorunda değilsin. Hazır CLMS katmanlarını bağımsız değişken, referans veri veya karşılaştırma ürünü olarak kullanmak hem analizi zenginleştirebilir hem de Avrupa veri ekosistemine hâkimiyetini gösterir.','access':'CLMS web sitesi ve Data Viewer üzerinden ürünler keşfedilebilir; ürüne göre indirme ve servis/API seçenekleri değişebilir. Bazı CLMS koleksiyonları CDSE ekosistemi üzerinden de erişilebilir.','you':'CBS geçmişin nedeniyle CLMS senin için Sentinel görevleri kadar önemli. Arazi/şehir katmanlarını çevresel ve atmosferik analizlerle birleştirmek AÇA odaklı çalışmalar için özellikle anlamlı.','idea':'Bir Ankara ilçesinde CLMS arazi örtüsü/imperviousness ürünleri ile Sentinel-2’den üretilen kentsel değişim göstergelerini karşılaştır ve uyumsuzluk alanlarını analiz et.','concepts':'CLC · Urban Atlas · HRL · EGMS','url':'https://land.copernicus.eu/en/products'},
 {'topic':'Eionet ve Reportnet: verinin kurumsal yolculuğu','category':'EEA / Veri Yönetişimi','what':'Eionet, Avrupa Çevre Ajansı ile üye ve işbirliği ülkelerindeki kurumları birbirine bağlayan çevre bilgi ağıdır. Reportnet ise çevresel raporlama ve veri akışlarının yürütülmesinde kullanılan altyapıdır. Burada konu yalnız teknik veri formatı değil; veri sorumluluğu, raporlama takvimi, kalite ve kurumsal iş akışıdır.','why':'AÇA’da çalışmak isteyen bir CBS/EO uzmanı için yalnız uydu analizi bilmek yeterli değildir. Verinin ulusal kurumdan Avrupa düzeyindeki değerlendirmeye nasıl ulaştığını anlamak, Eionet ekosistemini kavramanın temelidir.','access':'Eionet/Reportnet sayfalarındaki dataflow ve raporlama kaynakları üzerinden hangi çevre temasının hangi veri akışıyla raporlandığını inceleyebilirsin.','you':'Bakanlık deneyimini teknik CBS becerisiyle birleştirebileceğin alan tam olarak burası. Ulusal veri üretimi ile Avrupa çevre veri yönetişimi arasındaki köprüyü öğrenmek SNE profiline doğrudan katkı sağlar.','idea':'Bir çevre temasını seçip Türkiye’deki veri üretim zinciri ile ilgili Eionet/Reportnet veri akışını süreç, veri modeli ve CBS birlikte çalışabilirliği açısından eşleştir.','concepts':'Eionet · dataflow · reporting obligation · data governance','url':'https://www.eionet.europa.eu/reportnet/dataflows'},
]

def clean(s): return re.sub(r'\s+',' ',s or '').strip()
def potential(title,kind):
 t=title.lower()
 if any(k in t for k in ['sne','seconded national','ulusal uzman','geçici görevli']): return 'YÜKSEK — AÇA/SNE hedefiyle doğrudan ilgili. Uygunluk koşulları, kurum içi başvuru yolu ve son tarihi kontrol et.'
 if kind=='career' and any(k in t for k in ['vacanc','expert','ilan']): return 'YÜKSEK — EEA/AÇA kariyer fırsatı olabilir. CBS, Earth Observation, çevre verisi ve uzmanlık şartlarını kontrol et.'
 if any(k in t for k in ['sentinel','openeo','api','dataset','product','stac','odata','land cover']): return 'YÜKSEK — Teknik öğrenme, Türkiye uygulaması ve CV/makale çıktısına dönüşme potansiyeli var.'
 if kind=='eionet' or any(k in t for k in ['eionet','reportnet']): return 'ORTA-YÜKSEK — Avrupa çevre veri akışlarını ve veri yönetişimini öğrenmek AÇA profiline doğrudan katkı sağlar.'
 return 'ORTA — Somut veri, yöntem veya uygulama örneği içeriyorsa teknik nota ya da küçük uygulamaya dönüştürülebilir.'

def scrape(name,url,kind):
 r=requests.get(url,headers=HEAD,timeout=35); r.raise_for_status(); soup=BeautifulSoup(r.text,'html.parser'); items=[]
 for a in soup.find_all('a',href=True):
  title=clean(a.get_text(' ',strip=True)); low=title.lower()
  if len(title)<12 or not any(k in low for k in KEYWORDS): continue
  href=urljoin(url,a['href'])
  if href.startswith(('mailto:','javascript:')): continue
  parent=a.parent
  context=clean(parent.get_text(' ',strip=True))[:650] if parent else title
  uid=hashlib.sha1((name+'|'+href+'|'+title).encode()).hexdigest()[:16]
  items.append({'id':uid,'source':name,'kind':kind,'title':title,'url':href,'summary':context,'potential':potential(title,kind)})
 seen=set(); out=[]
 for x in items:
  if x['url'] not in seen: seen.add(x['url']); out.append(x)
 return out[:70]

def main():
 old=[]
 if OUT.exists():
  try: old=json.loads(OUT.read_text(encoding='utf-8')).get('items',[])
  except: pass
 oldmap={x['id']:x for x in old}; now=datetime.now(timezone.utc); allitems=[]; errors=[]
 for n,u,k in SOURCES:
  try: allitems += scrape(n,u,k)
  except Exception as e: errors.append(f'{n}: {e}')
 uniq={x['id']:x for x in allitems}; items=list(uniq.values())
 for x in items: x['first_seen']=oldmap.get(x['id'],{}).get('first_seen',now.isoformat())
 # 3 daily runs rotate the curriculum naturally; device tracks completed lessons separately.
 slot=(now.hour//8)
 lesson=LESSONS[(now.toordinal()*3+slot)%len(LESSONS)]
 OUT.parent.mkdir(parents=True,exist_ok=True)
 OUT.write_text(json.dumps({'updated_at':now.isoformat(),'items':items,'lesson':lesson,'curriculum':LESSONS,'errors':errors},ensure_ascii=False,indent=2),encoding='utf-8')
 print(f'{len(items)} items; lesson={lesson["topic"]}; errors={errors}')
if __name__=='__main__': main()
